zapConf:
  level: info
  format: console
  prefix: "[C2KV]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
dbConfig:
  dbPath: "./c2kv"
  walConfig:
    walDirPath: "./c2kv/wal"
  memConfig:
    memtableSize: 2048
    memtableNums: 10
  valueLogConfig:
    valueLogDir: "./c2kv/vlog"
  indexConfig:
    indexDir: "./c2kv/vlog/index"
raftConfig:
  electionTick: 100
  heartbeatTick: 100
  eAddr: 172.16.60.96:2345
  peers:
    - name: "node1"
      id  : 1
      iAddr: 172.16.60.96:7878
    - name: "node2"
      id  : 2
      iAddr: 172.16.60.97:7878
    - name: "node3"
      id  : 3
      iAddr: 172.16.60.98:7878