FROM golang:1.19

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ADD . /app
WORKDIR /app

RUN go build  -o c2kv

EXPOSE 2345 7878

#CMD ["dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./c2kv"]