zapConfig:
  level: info
  format: console
  prefix: "[C2KV]"
  director: "./var/c2kv/log"
  showLine: true
  encodeLevel: LowercaseColorLevelEncoder
  logInConsole: "true"
  maxAge: 10
dbConfig:
  dbPath: "./var/c2kv/data"
  walConfig:
    walDirPath: "./var/c2kv/data/wal"
    segmentSize: 60
    syncMode: "always"
    syncIntervalMs: 100
    walStateCheckpoint: 64
  memConfig:
    memTableSize: 2048
    memTablePipeSize: 1
    memTableNums: 1
    concurrency: 5
  valueLogConfig:
    valueLogDir: "./var/c2kv/data/vlog"
    partitionNums: 3
    partitionHash: "fnv64a"
    sstSize: 60
raftConfig:
  electionTick: 1000
  heartbeatTick: 100
  requestTimeOut: 5000
  maxInflightMsg: 1024
  maxSizePerMsg: 4194304
  eAddr: 172.29.0.13:2345
  iAddr: 172.29.0.13:7878
  peers:
    - name: node1
      id: 1
      iAddr: 172.29.0.11:7878
      eAddr: 172.29.0.11:2345
    - name: node2
      id: 2
      iAddr: 172.29.0.12:7878
      eAddr: 172.29.0.12:2345
    - name: node3
      id: 3
      iAddr: 172.29.0.13:7878
      eAddr: 172.29.0.13:2345
