FROM golang:1.20
# intsall dlv
RUN go install github.com/go-delve/delve/cmd/dlv@v1.20.0

# install system tools
RUN apt-get update && apt-get install -y ssh && apt-get install -y bash &&  apt-get install -y vim && apt-get install -y net-tools

# intsall SSH
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN echo 'root:root1234' | chpasswd

# build c2kv
RUN mkdir -p /app/src
RUN mkdir -p /app/scripts
COPY . /app/src
COPY ./deploy/dev/config_dev.yaml /app/
COPY ./scripts /app/scripts/
RUN chmod +x /app/scripts/*.sh
COPY ./scripts/run_dev.sh /app/
ENV GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
RUN cd /app/src && go build -o ../c2kv

CMD /usr/sbin/sshd -D
#ENTRYPOINT ["/app/scripts/run_dev.sh"]

# c2kv expose ports
EXPOSE 2345 7878