FROM golang:1.24

RUN go install github.com/go-delve/delve/cmd/dlv@v1.20.0 && \
    # system-tool
    apt-get update && \
    apt-get install -y ssh &&  \
    apt-get install -y bash &&  \
    apt-get install -y vim &&  \
    apt-get install -y net-tools && \
    # install  ssh
    mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    echo 'root:root1234' | chpasswd

# build c2kv
ENV GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
WORKDIR /code/src
COPY . .
COPY ./deploy/dev/config_dev.yaml /code/
WORKDIR /code/src/src
RUN go build -o c2kv && mv c2kv /usr/bin/
COPY ./scripts /code/scripts
RUN chmod +x /code/scripts/*.sh

# start c2kv
EXPOSE 2345 7878 22 40000
#ENTRYPOINT ["/app/scripts/run_dev.sh"]
CMD /usr/sbin/sshd -D