// Code generated by MockGen. DO NOT EDIT.
// Source: ./db.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	sync "sync"

	marshal "github.com/Mulily0513/C2KV/db/marshal"
	pb "github.com/Mulily0513/C2KV/pb"
	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AppliedIndex mocks base method.
func (m *MockStorage) AppliedIndex() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppliedIndex")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// AppliedIndex indicates an expected call of AppliedIndex.
func (mr *MockStorageMockRecorder) AppliedIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppliedIndex", reflect.TypeOf((*MockStorage)(nil).AppliedIndex))
}

// AppliedTerm mocks base method.
func (m *MockStorage) AppliedTerm() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppliedTerm")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// AppliedTerm indicates an expected call of AppliedTerm.
func (mr *MockStorageMockRecorder) AppliedTerm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppliedTerm", reflect.TypeOf((*MockStorage)(nil).AppliedTerm))
}

// Apply mocks base method.
func (m *MockStorage) Apply(kvs []*marshal.KV) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", kvs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockStorageMockRecorder) Apply(kvs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockStorage)(nil).Apply), kvs)
}

// Close mocks base method.
func (m *MockStorage) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// Entries mocks base method.
func (m *MockStorage) Entries(lo, hi uint64) ([]*pb.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Entries", lo, hi)
	ret0, _ := ret[0].([]*pb.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Entries indicates an expected call of Entries.
func (mr *MockStorageMockRecorder) Entries(lo, hi interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entries", reflect.TypeOf((*MockStorage)(nil).Entries), lo, hi)
}

// FirstIndex mocks base method.
func (m *MockStorage) FirstIndex() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstIndex")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// FirstIndex indicates an expected call of FirstIndex.
func (mr *MockStorageMockRecorder) FirstIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstIndex", reflect.TypeOf((*MockStorage)(nil).FirstIndex))
}

// Get mocks base method.
func (m *MockStorage) Get(key []byte) (*marshal.KV, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*marshal.KV)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), key)
}

// InitialState mocks base method.
func (m *MockStorage) InitialState() pb.HardState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitialState")
	ret0, _ := ret[0].(pb.HardState)
	return ret0
}

// InitialState indicates an expected call of InitialState.
func (mr *MockStorageMockRecorder) InitialState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitialState", reflect.TypeOf((*MockStorage)(nil).InitialState))
}

// PersistHardState mocks base method.
func (m *MockStorage) PersistHardState(hs pb.HardState, wg *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PersistHardState", hs, wg)
}

// PersistHardState indicates an expected call of PersistHardState.
func (mr *MockStorageMockRecorder) PersistHardState(hs, wg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistHardState", reflect.TypeOf((*MockStorage)(nil).PersistHardState), hs, wg)
}

// PersistUnstableEnts mocks base method.
func (m *MockStorage) PersistUnstableEnts(entries []*pb.Entry, wg *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PersistUnstableEnts", entries, wg)
}

// PersistUnstableEnts indicates an expected call of PersistUnstableEnts.
func (mr *MockStorageMockRecorder) PersistUnstableEnts(entries, wg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistUnstableEnts", reflect.TypeOf((*MockStorage)(nil).PersistUnstableEnts), entries, wg)
}

// Remove mocks base method.
func (m *MockStorage) Remove() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove")
}

// Remove indicates an expected call of Remove.
func (mr *MockStorageMockRecorder) Remove() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockStorage)(nil).Remove))
}

// Scan mocks base method.
func (m *MockStorage) Scan(lowKey, highKey []byte) ([]*marshal.KV, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", lowKey, highKey)
	ret0, _ := ret[0].([]*marshal.KV)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockStorageMockRecorder) Scan(lowKey, highKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockStorage)(nil).Scan), lowKey, highKey)
}

// StableIndex mocks base method.
func (m *MockStorage) StableIndex() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StableIndex")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// StableIndex indicates an expected call of StableIndex.
func (mr *MockStorageMockRecorder) StableIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StableIndex", reflect.TypeOf((*MockStorage)(nil).StableIndex))
}

// Term mocks base method.
func (m *MockStorage) Term(i uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Term", i)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Term indicates an expected call of Term.
func (mr *MockStorageMockRecorder) Term(i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Term", reflect.TypeOf((*MockStorage)(nil).Term), i)
}

// Truncate mocks base method.
func (m *MockStorage) Truncate(index uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Truncate", index)
	ret0, _ := ret[0].(error)
	return ret0
}

// Truncate indicates an expected call of Truncate.
func (mr *MockStorageMockRecorder) Truncate(index interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Truncate", reflect.TypeOf((*MockStorage)(nil).Truncate), index)
}
